### ISSUE TITLE
Files/categories not loading

### ISSUE THREAD

**Issue by adtorres0503** [keiffster/y-bot#1]
Hi Keith,

Thank you very much for this project.

I'm trying to load this y-bot into Program-Y v3.7 but somehow it is not loading the files/categories. Is there any configuration that I need to do?

**Comment by keiffster** [comment]
Hi, need a little bit more info

What OS are you running 
Which version of Python 

Did you follow the installation instructions from Programy wiki and use the Admin tool to install y-bot ?

Which client are you using

Are there any errors on the screen

Are there any errors in the log files 

Regards 

Keith
keith@keithsterling.com
07771 597630

**Comment by adtorres0503** [comment]
Hi Keith,

Thank you very much. I managed to make it work by using Admin tool as per your advice.

Regards,
Allan
